#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp system/blockMeshDict.orig system/blockMeshDict
foamDictionary -entry vertices -value system/blockMeshDict | tr "()" " \n" > system/old_vertices.txt
foamDictionary -entry edges -value system/blockMeshDict | tr -d "[:alpha:]" | tr "()" " \n" > system/old_edges.txt
foamDictionary -entry blocks -value system/blockMeshDict | tr "h()" "\n " | tr -d "[:alpha:]" > system/old_blocks.txt
runApplication -s blockMesh python system/blockMesh.py
runApplication -s set.vertices foamDictionary -entry vertices -set "`cat system/vertices.txt`" system/blockMeshDict
runApplication -s set.edges foamDictionary -entry edges -set "`cat system/edges.txt`" system/blockMeshDict
runApplication -s set.blocks foamDictionary -entry blocks -set "`cat system/blocks.txt`" system/blockMeshDict
runApplication blockMesh

mkfifo vorticity.txt
runApplication $(getApplication)
