#!/usr/bin/env bash
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication -s parse_mesh python system/parse_mesh.py

# scikit-fem parallel path

coproc runApplication -s potential python system/potential.py quads.msh

# OpenFOAM parallal path

runApplication -s left python system/left.py
runApplication potentialFoam -writePhi

# end of parallel paths

wait  # for scikit-fem
